FROM node:alpine
WORKDIR '/app'
COPY ./package.json ./

RUN export http_proxy=http://192.168.1.10:3128/
RUN export https_proxy=http://192.168.1.10:3128/
RUN npm config set registry http://registry.npmjs.org/
RUN npm config set http-proxy http://192.168.1.10:3128/
RUN npm config set https-proxy http://192.168.1.10:3128/
RUN npm config set proxy http://192.168.1.10:3128/
RUN npm set strict-ssl false

RUN npm install
COPY . .

CMD ["npm", "run", "start"]