---

- name: Error Handling Playbook example
  hosts: all
  become: yes

  tasks:

  - name: Task number 1
    yum: name=treeeee state=latest
    ignore_errors: yes

  - name: Task number 2
    shell: echo Hello World!!!
    register: results
#    failed_when: "'World' in results.stdout"
    failed_when: results.rc == 0

  - debug:
      var: results

  - name: Task number 3
    shell: echo Privet Mir!!!