---
- name: Install Apache and upload my Web Page
  hosts: all
  become: yes

  vars:
     source_file: ./index.html
     destin_file: /var/www/html

  tasks:
  - name: Install Apache Web Server
    apt: name=apache2 state=latest

  - name: Copy My Homepage to Servers
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    notify: Restart Apache

  - name: Start Web Servers and Make It Enabled on boot
    service: name=apache2 state=started enabled=yes


  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted
